name: Test coverage
on: [push]
jobs:
  super-lint:
    name: Test coverage

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint Code Base
        uses: github/super-linter/slim@v4

      - name: Install dependencies
        run: npm install
        
      - name: Run test coverage
        run: npm test -- --coverage
        
      - name: Upload test coverage
        uses: codecov/codecov-action@v2
